name: Basic Tests
on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      # ---
      - name: Debug
        run: ls -la .

      # ---
      - run: apt-get update
      - run: apt-get install -y mosquitto git
      - run: apt-get install -y python3 python3-pip

      # ---
      - run: pip install -r ./tests/requirements.txt
      - run: pip install -r ./platform/requirements.txt
      - run: pip install ./client/
      - run: pip install ./platform/

      # ---
      - run: mosquitto -d

      # ---
      - run: python3 ./platform/deploy/pza-py-platform-run.py ./tests/pza/tree.json &

      # ---
      - name: Execute tests
        working-directory: tests
        run: robot robot/*
      #   env:
      #     PYTHONPATH: "."
      #     COVERAGE_PROCESS_START: "NO"


      # - name: Covergae Report
      #   run: coverage report


      # - name: Execute tests to html
      #   run: coverage run --source='panduza' -m behave -f html -o acceptance/report/test.html
      #   env:
      #     PYTHONPATH: ".."
      #     COVERAGE_PROCESS_START: "NO"

      # - name: Coverage Report to html
      #   run: coverage html -d acceptance/report/coverage

      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: acceptance-report
      #     path: acceptance/report


      - run: echo "🎉 Basic Tests finished !"

