name: Basic Tests
on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      # ---
      - run: echo "${GITHUB_WORKSPACE}"
      - name: Debug
        run: echo "`ls -la ${GITHUB_WORKSPACE}`"

      # ---
      - run: apt-get update
      - run: apt-get install -y mosquitto git
      - run: apt-get install -y python3 python3-pip

      # ---
      - run: pip install ${GITHUB_WORKSPACE}/client
      # - run: pip install ${GITHUB_WORKSPACE}/platform

      # ---
      - run: mosquitto -d

      # ---
      # - run: python3 ${GITHUB_WORKSPACE}/platform/deploy/pza-py-platform-run.py


      # - name: Execute tests
      #   run: coverage run --source='panduza' -m behave
      #   env:
      #     PYTHONPATH: "."
      #     COVERAGE_PROCESS_START: "NO"


      # - run: echo "`ls -la ${GITHUB_WORKSPACE}`"


      # - name: Covergae Report
      #   run: coverage report


      # - name: Execute tests to html
      #   run: coverage run --source='panduza' -m behave -f html -o acceptance/report/test.html
      #   env:
      #     PYTHONPATH: ".."
      #     COVERAGE_PROCESS_START: "NO"

      # - name: Coverage Report to html
      #   run: coverage html -d acceptance/report/coverage

      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: acceptance-report
      #     path: acceptance/report


      - run: echo "🎉 Basic Tests finished !"

