name: Action to test the Python client
on: [push]

env:
  PLATFORM_PY_BRANCH: main

jobs:
  Tests:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - run: echo "${GITHUB_WORKSPACE}"

      - run: apt-get update
      - run: apt-get install -y mosquitto git

      - run: apt-get install -y python3 python3-pip
      - run: pip install git+https://github.com/behave/behave
      - run: pip install PyHamcrest coverage loguru
      - run: pip install behave-html-formatter

      - run: pip install git+https://github.com/Panduza/panduza-py-platform@$PLATFORM_PY_BRANCH

      - run: mosquitto -d

      - name: Debug
        run: echo "`ls -la ${GITHUB_WORKSPACE}`"


      - name: Execute tests
        run: coverage run --source='panduza' -m behave
        env:
          PYTHONPATH: "."
          COVERAGE_PROCESS_START: "NO"


      - run: echo "`ls -la ${GITHUB_WORKSPACE}`"


      - name: Covergae Report
        run: coverage report


      - name: Execute tests to html
        run: coverage run --source='panduza' -m behave -f html -o acceptance/report/test.html
        env:
          PYTHONPATH: ".."
          COVERAGE_PROCESS_START: "NO"

      - name: Coverage Report to html
        run: coverage html -d acceptance/report/coverage

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: acceptance-report
          path: panduza-py-platform/acceptance/report


      - run: echo "🎉 Test finished !"

